'use client';
import {useEffect,useState,useMemo} from 'react';
import {GraduationCap,Download,Trash2,RefreshCw,Search,FileText,Users,CheckCircle2,AlertCircle,ClipboardCheck} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from '@/components/ui/table';
import {Checkbox} from '@/components/ui/checkbox';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {AlertDialog,AlertDialogContent,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from '@/components/ui/alert-dialog';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {units,marks} from '@/lib/curriculum';
import {api,type SavedRun,SignInCard} from './game-app';
function csvDownload(name:string,rows:(string|number)[][]){const csv=rows.map(row=>row.map(value=>{let s=String(value??'');if(/^[\s]*[=+@-]/.test(s))s="'"+s;return '"'+s.replaceAll('"','""')+'"'}).join(',')).join('\r\n');const url=URL.createObjectURL(new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8;'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
export default function TeacherDashboard({teacher,user}:{teacher:boolean;user:boolean}){
 const [runs,setRuns]=useState<SavedRun[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');
 const [search,setSearch]=useState(''),[unit,setUnit]=useState('all'),[selected,setSelected]=useState<string[]>([]),[confirm,setConfirm]=useState(false),[review,setReview]=useState<SavedRun|null>(null),[comment,setComment]=useState('');
 const load=async()=>{if(!teacher){setLoading(false);return}setLoading(true);try{const d=await api('/api/teacher');setRuns(d.runs);setSelected([]);setError('')}catch(e){setError((e as Error).message)}finally{setLoading(false)}};
 useEffect(()=>{load()},[teacher]);
 const shown=runs.filter(r=>(unit==='all'||r.unit===Number(unit))&&((r.name||'')+' '+(r.email||'')).toLowerCase().includes(search.toLowerCase()));
 const students=useMemo(()=>{const map=new Map<string,{name:string;email:string;scores:number[];attempts:number}>();runs.forEach(r=>{const id=r.user_id||r.email||'';if(!map.has(id))map.set(id,{name:r.name||'',email:r.email||'',scores:[0,0,0,0,0,0],attempts:0});const s=map.get(id)!;s.scores[r.unit-1]=Math.max(s.scores[r.unit-1],r.score);s.attempts++});return [...map.values()].filter(s=>(s.name+' '+s.email).toLowerCase().includes(search.toLowerCase()))},[runs,search]);
 const exportProgress=()=>csvDownload('VocaQuest-Student-Progress.csv',[['Student name','Email',...units.map(u=>'Unit '+u.id+' /100'),'Total /600','Overall %','Final mark /10'],...students.map(s=>{const total=s.scores.reduce((a,b)=>a+b,0);return [s.name,s.email,...s.scores,total,(total/6).toFixed(2),marks(total/6)]})]);
 const exportResponses=()=>csvDownload('VocaQuest-Responses.csv',[['Name','Email','Unit','Mode','Score /100','Learning mark /10','Completed','Writing (unmarked)','Teacher feedback','Recording (unmarked)'],...shown.map(r=>[r.name||'',r.email||'',r.unit,r.mode,r.score,r.score/10,r.completed_at,r.writing||'',r.teacher_comment||'',r.recording?'Submitted':'Not submitted'])]);
 if(!user)return <SignInCard/>;if(!teacher)return <div className="empty-panel"><GraduationCap size={42}/><h2>Learning Skills Marks</h2><p>Class records are reserved for Ms. Amina Qatan’s teacher account.</p><p>Your own results and feedback are available under My progress.</p></div>;
 return <><div className="page-heading"><div><div className="eyebrow">MS. AMINA QATAN · TEACHER SPACE</div><h1>Learning Skills Marks</h1><p>Review adventures, respond to writing, and track class progress.</p></div><button className="secondary-button" onClick={load} disabled={loading}><RefreshCw size={18}/>Refresh</button></div>{error&&<div role="alert" className="error-banner"><AlertCircle size={19}/>{error}</div>}{notice&&<div role="status" className="success-banner"><CheckCircle2 size={19}/>{notice}</div>}<div className="stats-grid"><div className="stat-card"><Users/><div><small>Students with results</small><strong>{new Set(runs.map(r=>r.user_id)).size}</strong></div></div><div className="stat-card"><FileText/><div><small>Completed adventures</small><strong>{runs.length}</strong></div></div><div className="stat-card"><ClipboardCheck/><div><small>Practice submissions</small><strong>{runs.filter(r=>r.writing||r.recording).length}</strong></div></div></div>
 <div className="teacher-toolbar"><label className="search-box"><Search size={18}/><input aria-label="Search students by name or email" value={search} placeholder="Search student name or email" onChange={e=>setSearch(e.target.value)}/></label></div>
 <Tabs defaultValue="progress"><TabsList className="lesson-tab-list"><TabsTrigger value="progress">Student progress</TabsTrigger><TabsTrigger value="responses">Responses, speaking & writing</TabsTrigger></TabsList><TabsContent value="progress"><div className="section-heading"><h2>Progress report</h2><button className="secondary-button" onClick={exportProgress} disabled={!students.length}><Download size={17}/>Export CSV</button></div><p className="small-note">Best result per unit. The overall mark uses all six units: total ÷ 600 × 10. An overall score of 95% or above earns 10/10. Tongue twisters and picture writing are unmarked practice.</p><div className="table-card"><Table><TableHeader><TableRow><TableHead>Student</TableHead>{units.map(u=><TableHead key={u.id}>U{u.id}<small>/100</small></TableHead>)}<TableHead>Total<small>/600</small></TableHead><TableHead>Overall %</TableHead><TableHead>Final mark /10</TableHead></TableRow></TableHeader><TableBody>{students.map(s=>{const total=s.scores.reduce((a,b)=>a+b,0);return <TableRow key={s.email+s.name}><TableCell><b>{s.name}</b><small>{s.email}</small></TableCell>{s.scores.map((score,i)=><TableCell key={i}>{score===0?'—':score}</TableCell>)}<TableCell><b>{total}</b></TableCell><TableCell>{(total/6).toFixed(1)}%</TableCell><TableCell><span className={total/6>=95?'mark-badge bonus':'mark-badge'}>{marks(total/6)}</span></TableCell></TableRow>})}</TableBody></Table>{!students.length&&<div className="empty-panel"><Users size={30}/><h3>{loading?'Loading class progress…':search?'No students match your search.':'Your class progress will appear here.'}</h3><p>Students need to finish a saved adventure first.</p></div>}</div></TabsContent>
 <TabsContent value="responses"><div className="section-heading response-toolbar"><Select value={unit} onValueChange={setUnit}><SelectTrigger className="unit-filter"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">All worlds</SelectItem>{units.map(u=><SelectItem key={u.id} value={String(u.id)}>Unit {u.id} · {u.title}</SelectItem>)}</SelectContent></Select><div><button className="secondary-button" onClick={exportResponses} disabled={!shown.length}><Download size={17}/>Export</button><button className="danger-button" onClick={()=>setConfirm(true)} disabled={!selected.length||busy}><Trash2 size={16}/>Delete selected ({selected.length})</button></div></div><div className="table-card"><Table><TableHeader><TableRow><TableHead><Checkbox aria-label="Select up to 100 visible responses" checked={shown.length>0&&shown.slice(0,100).every(r=>selected.includes(r.id))} onCheckedChange={v=>setSelected(v?shown.slice(0,100).map(r=>r.id):[])}/></TableHead><TableHead>Student</TableHead><TableHead>World</TableHead><TableHead>Learning score</TableHead><TableHead>Writing practice</TableHead><TableHead>Speaking practice</TableHead><TableHead>Date</TableHead><TableHead>Details</TableHead></TableRow></TableHeader><TableBody>{shown.map(r=><TableRow key={r.id}><TableCell><Checkbox aria-label={'Select response by '+r.name+' for unit '+r.unit} checked={selected.includes(r.id)} disabled={!selected.includes(r.id)&&selected.length>=100} onCheckedChange={v=>setSelected(s=>v?[...s,r.id]:s.filter(id=>id!==r.id))}/></TableCell><TableCell><b>{r.name}</b><small>{r.email}</small></TableCell><TableCell>Unit {r.unit}<small>{r.mode}</small></TableCell><TableCell><b>{r.score}%</b><small>{r.score/10}/10 marks</small></TableCell><TableCell><span className="status-tag">{r.writing?'Submitted · unmarked':'Not submitted'}</span></TableCell><TableCell>{r.recording?'Recorded · unmarked':'Not submitted'}</TableCell><TableCell>{new Date(r.completed_at).toLocaleDateString()}</TableCell><TableCell><button className="text-button" onClick={()=>{setReview(r);setComment(r.teacher_comment||'');setError('')}}>View response</button></TableCell></TableRow>)}</TableBody></Table>{!shown.length&&<div className="empty-panel"><FileText size={30}/><h3>{loading?'Loading responses…':'No responses to display.'}</h3></div>}</div><p className="small-note">Deleting an attempt also removes its recording and writing and may change the student’s best score and unlocked worlds.</p></TabsContent></Tabs>{runs.length>=1000&&<p className="error-banner">This report shows the most recent 1,000 attempts. Totals reflect these displayed records.</p>}
 <AlertDialog open={confirm} onOpenChange={setConfirm}><AlertDialogContent><AlertDialogTitle>Delete {selected.length} selected responses?</AlertDialogTitle><AlertDialogDescription>These attempts, their recordings, writing and teacher feedback will be permanently removed. Progress will be recalculated from the remaining attempts.</AlertDialogDescription><AlertDialogFooter><AlertDialogCancel>Cancel</AlertDialogCancel><AlertDialogAction className="bg-red-700 text-white" onClick={async()=>{setBusy(true);try{await api('/api/teacher',{action:'delete',ids:selected});setNotice('Selected responses deleted.');await load()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}>Delete responses</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 <Dialog open={!!review} onOpenChange={v=>{if(!v)setReview(null)}}><DialogContent className="teacher-review-dialog"><DialogTitle>{review?.name} · Unit {review?.unit}</DialogTitle><DialogDescription>{review?.email} · {review?.score}% learning score</DialogDescription>{review&&<>{!!review.recording&&<section className="review-speaking"><h3>Tongue-twister practice</h3><audio controls preload="metadata" src={"/api/voice?id="+encodeURIComponent(review.id)}/><p className="small-note">Unmarked practice · three repetitions.</p></section>}{review.writing?<><div className="writing-prompt"><b>Picture-writing task</b><p>{units[review.unit-1].writing}</p></div><blockquote className="student-writing">{review.writing}</blockquote><p className="small-note">Picture writing is unmarked practice. You can leave a helpful comment below.</p><label className="field-label" htmlFor="teacher-feedback">Feedback for the student</label><textarea id="teacher-feedback" rows={3} maxLength={1500} value={comment} onChange={e=>setComment(e.target.value)} placeholder="One strength and one specific next step…"/>{error&&<p role="alert" className="error-banner">{error}</p>}<button disabled={busy} className="primary-button" onClick={async()=>{setBusy(true);try{await api('/api/teacher',{action:'comment',id:review.id,comment});setReview(null);setNotice('Feedback saved.');await load()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}>{busy?'Saving…':'Save feedback'}</button></>:<p className="info-box">This student has not submitted a picture description for this attempt.</p>}<details className="transcript"><summary>View challenge answers</summary>{review.answers&&review.question_ids&&(JSON.parse(review.question_ids) as number[]).map((id,i)=>{const q=units[review.unit-1].questions[id],a=(JSON.parse(review.answers!) as string[])[i];return <div className="review-answer" key={i}><b>{i+1}. {q.prompt}</b><p>Student: {a}</p><p>Correct: {q.answer}</p></div>})}</details></>}</DialogContent></Dialog></>
}
